from turtle import *
from random import randint
speed("fast")
bgcolor("black")
sety(-90)
pencolor("white")
left(45)
forward(180)
right(45)
forward(45)
right(135)
forward(180)
right(45)
forward(45)
pencolor("black")
forward(90)
right(90)
forward(90)
right(90)
speed(1)
pencolor("red")
forward(180)
pencolor("yellow")
right(45)
forward(35)
pencolor("red")
speed("fast")
for i in range(14):
    if randint(0,1) == 1:
        left(x:=randint(0,60))
        forward(180)
        forward(-180)
        right(x)
    else:
        right(x:=randint(0,60))
        forward(180)
        forward(-180)
        left(x)
end_fill()
done()