from turtle import *
from random import randint
speed("fast")
bgcolor("black")
sety(-90)
pencolor("white")
left(45)
forward(180)
right(45)
forward(45)
right(135)
forward(180)
right(45)
forward(45)
pencolor("black")
forward(90)
right(90)
forward(90)
right(90)
speed(1)
pencolor("red")
forward(180)
if randint(0,1) == 0:
    pencolor("yellow")
    right(45)
    forward(35)
    pencolor("red")
    forward(90)
else:
    pencolor("orange")
    left(randint(45, 60))
    forward(180)
speed("fast")
pencolor("red")
for i in range(25):
    if randint(0,1) == 1:
        left(x:=randint(0,180))
        forward(90)
        forward(-90)
        right(x)
    else:
        right(x:=randint(0,180))
        forward(90)
        forward(-90)
        left(x)
end_fill()
done()